### ISSUE TITLE
Ubuntu 17.10 system freezes

### ISSUE THREAD

**Issue by danmash** [oleid/gnome-shell-teatime#42] opened 2017-11-28 09:42 UTC
Timer works well but when time's up ALL system just freezes and only hard reset would help

**Comment by oleid** [comment] 2017-11-28 20:59
Please add more information like what other extensions you are using and which version you are using. I'm running it myself on Ubuntu 17.10 without issues.

**Comment by danmash** [comment] 2017-11-29 07:51
I just installed ubuntu 17.10 and there are no other extensions. Your extension is the first one.

**Comment by oleid** [comment] 2017-11-30 08:30
What graphic hardware are you using? And are you using the default session ("Ubuntu" on my system), or are you using the classical Xorg version ("Ubuntu Xorg" or something similar).

I still cannot reproduce the issue. Which is why I think it might be related to the graphic driver used on your machine. You could disable "Full screen notifications" in this case. That might work around the issue.

**Comment by oleid** [comment] 2021-02-21 21:10
ubuntu is now outdated, closing this.

**Closed by oleid** 2021-02-21 21:10 UTC
Labels: needmoreinfo, question
