### ISSUE TITLE
Overlay not closable

### ISSUE THREAD

**Issue by kelunik** [oleid/gnome-shell-teatime#21] opened 2015-02-27 14:08 UTC
Sometimes, the overlay is not closable and requires a `gnome-shell` restart.
I've currently no idea when that happens.

**Comment by oleid** [comment] 2015-02-27 14:13
I've noticed this on older gnome-shell versions, when the system hung. But not since 3.12. Sadly, I couldn't reproduce it either. I guess this must be some shell bug, but I really don't know.

**Comment by kelunik** [comment] 2015-02-27 14:29
```plain
kelunik@kelunik:~$ gnome-shell --version
GNOME Shell 3.14.3
```

It doesn't happen that often. I can keep working with that overlay, all clicks are working as normal but not received by the overlay itself.

**Comment by Nachtgast** [comment] 2017-06-25 15:28
If you do not click on the rotating teapot but on the darkened area, then overlays can not be closed

**Comment by oleid** [comment] 2018-03-18 20:43
Nachtgast, the widget representing the tea pot is only in the centre of the screen. We don't recieve events from the outside of the widget.

**Comment by xuiqzy** [comment] 2019-10-08 21:35
This still happens on Gnome on Wayland on Arch Linux with Gnome Shell Version 3.34.0+152+g0fdbde910. If Fullscreen Notifications are enabled, the overlay is placed in the top left corner above the tob bar and only a little bit higher than the tob bar and the width reaching approximately to the middle of the word Applications.
With Fullscreen Notifications disabled, everything is working as expected.

**Comment by oleid** [comment] 2021-02-21 21:12
Fullscreen notifications got removed, closing

**Closed by oleid** 2021-02-21 21:12 UTC
