### ISSUE TITLE
Icon not aligned vertically and doesn't scale with font

### ISSUE THREAD

**Issue by S1rn3wyark** [oleid/gnome-shell-teatime#30] opened 2016-05-04 21:09 UTC
The icon is not aligned vertically in MMOD Panel with Gnome Shell 3.18.4 (Ubuntu 16.04)

![teatime](https://cloud.githubusercontent.com/assets/19195308/15029279/2917d3ae-124d-11e6-8abd-dea18aa074b5.png)

**Comment by GuillaumeAmat** [comment] 2016-12-21 15:49
Furthermore, when using the accessibility *big text* mode, the icon does not grow like others.

**Comment by oleid** [comment] 2017-11-03 19:38
It does now align, however, the width of the drawing area isn't increased, while the height is.

**Comment by fbruetting** [comment] 2017-11-18 04:02
Duplicate of #24. Now the icon size fits, but the padding still is missing.

**Comment by oleid** [comment] 2017-11-22 00:41
@fbruetting I've experimented a little with Shell.GenericContainer, as used in i.e. the shell's keyboard indicator. It's all WIP and not cleaned up. But if you like, you could check if it solves your padding issue. 

https://github.com/oleid/gnome-shell-teatime/tree/better_handling_of_resize

**Comment by oleid** [comment] 2021-02-21 21:10
Outdated, should work as is

**Closed by oleid** 2021-02-21 21:10 UTC
